

2017-10-31 16:06:40,034 (kafkaagent-0.1 13481) <stderr> ERROR: Traceback (most recent call last):
2017-10-31 16:06:40,034 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
2017-10-31 16:06:40,035 (kafkaagent-0.1 13481) <stderr> ERROR:     msg = self.format(record)
2017-10-31 16:06:40,035 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
2017-10-31 16:06:40,035 (kafkaagent-0.1 13481) <stderr> ERROR:     return fmt.format(record)
2017-10-31 16:06:40,035 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/volttron/platform/agent/utils.py", line 357, in format
2017-10-31 16:06:40,035 (kafkaagent-0.1 13481) <stderr> ERROR:     return jsonapi.dumps(dct)
2017-10-31 16:06:40,036 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/volttron/platform/agent/json.py", line 68, in dumps
2017-10-31 16:06:40,036 (kafkaagent-0.1 13481) <stderr> ERROR:     return _dumps(data, **kwargs)
2017-10-31 16:06:40,036 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
2017-10-31 16:06:40,037 (kafkaagent-0.1 13481) <stderr> ERROR:     s = jsonmod.dumps(o, **kwargs)
2017-10-31 16:06:40,037 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/simplejson/__init__.py", line 397, in dumps
2017-10-31 16:06:40,037 (kafkaagent-0.1 13481) <stderr> ERROR:     **kw).encode(obj)
2017-10-31 16:06:40,038 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
2017-10-31 16:06:40,038 (kafkaagent-0.1 13481) <stderr> ERROR:     chunks = self.iterencode(o, _one_shot=True)
2017-10-31 16:06:40,038 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
2017-10-31 16:06:40,038 (kafkaagent-0.1 13481) <stderr> ERROR:     return _iterencode(o, 0)
2017-10-31 16:06:40,039 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 252, in default
2017-10-31 16:06:40,039 (kafkaagent-0.1 13481) <stderr> ERROR:     raise TypeError(repr(o) + " is not JSON serializable")
2017-10-31 16:06:40,040 (kafkaagent-0.1 13481) <stderr> ERROR: TypeError: ProduceResponse_v2(topics=[(topic=u'msg-from-volttron', partitions=[(partition=0, error_code=0, offset=2574, timestamp=-1)])], throttle_time_ms=0) is not JSON serializable


2017-10-31 16:06:43,749 (kafkaagent-0.1 13481) <stderr> ERROR: Traceback (most recent call last):
2017-10-31 16:06:43,750 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
2017-10-31 16:06:43,750 (kafkaagent-0.1 13481) <stderr> ERROR:     msg = self.format(record)
2017-10-31 16:06:43,751 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
2017-10-31 16:06:43,751 (kafkaagent-0.1 13481) <stderr> ERROR:     return fmt.format(record)
2017-10-31 16:06:43,751 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/volttron/platform/agent/utils.py", line 357, in format
2017-10-31 16:06:43,751 (kafkaagent-0.1 13481) <stderr> ERROR:     return jsonapi.dumps(dct)
2017-10-31 16:06:43,752 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/volttron/platform/agent/json.py", line 68, in dumps
2017-10-31 16:06:43,752 (kafkaagent-0.1 13481) <stderr> ERROR:     return _dumps(data, **kwargs)
2017-10-31 16:06:43,753 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/zmq/utils/jsonapi.py", line 40, in dumps
2017-10-31 16:06:43,753 (kafkaagent-0.1 13481) <stderr> ERROR:     s = jsonmod.dumps(o, **kwargs)
2017-10-31 16:06:43,753 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/simplejson/__init__.py", line 397, in dumps
2017-10-31 16:06:43,754 (kafkaagent-0.1 13481) <stderr> ERROR:     **kw).encode(obj)
2017-10-31 16:06:43,754 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 275, in encode
2017-10-31 16:06:43,754 (kafkaagent-0.1 13481) <stderr> ERROR:     chunks = self.iterencode(o, _one_shot=True)
2017-10-31 16:06:43,755 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 357, in iterencode
2017-10-31 16:06:43,755 (kafkaagent-0.1 13481) <stderr> ERROR:     return _iterencode(o, 0)
2017-10-31 16:06:43,755 (kafkaagent-0.1 13481) <stderr> ERROR:   File "/home/sol/workspace/volttron/env/local/lib/python2.7/site-packages/simplejson/encoder.py", line 252, in default
2017-10-31 16:06:43,756 (kafkaagent-0.1 13481) <stderr> ERROR:     raise TypeError(repr(o) + " is not JSON serializable")
2017-10-31 16:06:43,756 (kafkaagent-0.1 13481) <stderr> ERROR: TypeError: <BrokerConnection node_id=0 host=sol/127.0.1.1 port=9092> is not JSON serializable
2017-10-31 16:06:43,756 (kafkaagent-0.1 13481) <stderr> ERROR: Logged from file conn.py, line 875




